name: Release

on: 
  release:
    types: [published]

jobs:
  
  build-and-upload-artifacts:
    
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [ '17' ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} JDK ${{ matrix.java }}
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Execute jpackage
        run: ./gradlew --info --stacktrace jpackage
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: pacman-ui-fx-3d/build/jpackage

  download-and-release-artifacts:
    needs: build-and-upload-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download ALL artifacts
        uses: actions/download-artifact@v4
        with:
          path: pacman-ui-fx-3d/build/jpackage
          pattern: (*.exe|*.deb|*.dmg)
      - name: Release executables
        uses: softprops/action-gh-release@v1
        with:
          files: pacman-ui-fx-3d/build/jpackage/(*.exe|*.deb|*.dmg)     

