name: Release Artifacts

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pacman-ui-fx-2d-jdk-${{ matrix.java }}-${{ matrix.os }}-exe
          path: pacman-ui-fx-2d/build/jpackage/*.exe
