# This workflow builds executables for Windows, Linux and Mac-OS and attaches the 3D-version executables to the
# release (when a new release is published via the GitHub UI). 
# Note that this works for a multi-project and has to be slightly adapted for a single-project.

name: Release

on: 
  release:
    types: [published] # if this is omitted, the workflow starts 3 times when creating a release!

jobs:
  
  build-and-upload-artifacts:
    
    strategy:
      matrix:
        os:   [windows-latest]
        java: ['17']
      fail-fast: false

    runs-on: ${{ matrix.os }}
    name: Build and upload artifacts for ${{ matrix.os }} JDK ${{ matrix.java }}
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Execute jpackage
        run: ./gradlew --info --stacktrace jpackage

      # simplify these steps
      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: pacman-ui-fx-3d/build/jpackage/*.exe
          if-no-files-found: ignore
      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: pacman-ui-fx-3d/build/jpackage/*.deb
          if-no-files-found: ignore
      - name: Upload dmg
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: pacman-ui-fx-3d/build/jpackage/*.dmg
          if-no-files-found: ignore

  download-and-release-artifacts:
    needs: build-and-upload-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download ALL artifacts
        uses: actions/download-artifact@v4
        with:
          path: pacman-ui-fx-3d/build/jpackage
      - name: List files
        run: ls -R
      - name: Attach executables to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./pacman-ui-fx-3d/build/jpackage/macOS-latest/pacman-javafx-3d-1.0.dmg
            ./pacman-ui-fx-3d/build/jpackage/ubuntu-latest/pacman-javafx-3d_1.0-1_amd64.deb
            ./pacman-ui-fx-3d/build/jpackage/windows-latest/pacman-javafx-3d-1.0.exe
