on: [workflow_dispatch]
name: Create release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: build/jpackage/*.(exe|deb|dmg)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
